version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: lab_1_big_data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./raw_data:/raw_data
      - ./sql:/docker-entrypoint-initdb.d 
    restart: unless-stopped

volumes:
  postgres_data: